# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech.proto',
  package='speech',
  serialized_pb=_b('\n\x0cspeech.proto\x12\x06speech\"\xc7\x01\n\rSpeechRequest\x12\x1d\n\x04word\x18\x01 \x01(\x0e\x32\x0f.speech.Keyword\x12\x12\n\nconfidence\x18\x02 \x01(\x05\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12(\n\x02\x65q\x18\x04 \x01(\x0e\x32\x11.speech.Equalizer:\tSENSE_ONE\x12*\n\x08response\x18\x05 \x01(\x0e\x32\x13.speech.AudioFormat:\x03MP3\x12\x1c\n\rsampling_rate\x18\x06 \x01(\x05:\x05\x31\x36\x30\x30\x30*$\n\tEqualizer\x12\x08\n\x04NONE\x10\x00\x12\r\n\tSENSE_ONE\x10\x01**\n\x0b\x41udioFormat\x12\x07\n\x03MP3\x10\x00\x12\t\n\x05\x41\x44PCM\x10\x01\x12\x07\n\x03RAW\x10\x02*B\n\x07Keyword\x12\x08\n\x04NULL\x10\x00\x12\x0c\n\x08OK_SENSE\x10\x01\x12\x08\n\x04STOP\x10\x02\x12\n\n\x06SNOOZE\x10\x03\x12\t\n\x05\x41LEXA\x10\x04\x42\"\n\x18is.hello.speech.core.apiB\x06Speech')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EQUALIZER = _descriptor.EnumDescriptor(
  name='Equalizer',
  full_name='speech.Equalizer',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSE_ONE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=226,
  serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_EQUALIZER)

Equalizer = enum_type_wrapper.EnumTypeWrapper(_EQUALIZER)
_AUDIOFORMAT = _descriptor.EnumDescriptor(
  name='AudioFormat',
  full_name='speech.AudioFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MP3', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADPCM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAW', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=264,
  serialized_end=306,
)
_sym_db.RegisterEnumDescriptor(_AUDIOFORMAT)

AudioFormat = enum_type_wrapper.EnumTypeWrapper(_AUDIOFORMAT)
_KEYWORD = _descriptor.EnumDescriptor(
  name='Keyword',
  full_name='speech.Keyword',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK_SENSE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SNOOZE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALEXA', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=308,
  serialized_end=374,
)
_sym_db.RegisterEnumDescriptor(_KEYWORD)

Keyword = enum_type_wrapper.EnumTypeWrapper(_KEYWORD)
NONE = 0
SENSE_ONE = 1
MP3 = 0
ADPCM = 1
RAW = 2
NULL = 0
OK_SENSE = 1
STOP = 2
SNOOZE = 3
ALEXA = 4



_SPEECHREQUEST = _descriptor.Descriptor(
  name='SpeechRequest',
  full_name='speech.SpeechRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='speech.SpeechRequest.word', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='speech.SpeechRequest.confidence', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='speech.SpeechRequest.version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eq', full_name='speech.SpeechRequest.eq', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='speech.SpeechRequest.response', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampling_rate', full_name='speech.SpeechRequest.sampling_rate', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=16000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=224,
)

_SPEECHREQUEST.fields_by_name['word'].enum_type = _KEYWORD
_SPEECHREQUEST.fields_by_name['eq'].enum_type = _EQUALIZER
_SPEECHREQUEST.fields_by_name['response'].enum_type = _AUDIOFORMAT
DESCRIPTOR.message_types_by_name['SpeechRequest'] = _SPEECHREQUEST
DESCRIPTOR.enum_types_by_name['Equalizer'] = _EQUALIZER
DESCRIPTOR.enum_types_by_name['AudioFormat'] = _AUDIOFORMAT
DESCRIPTOR.enum_types_by_name['Keyword'] = _KEYWORD

SpeechRequest = _reflection.GeneratedProtocolMessageType('SpeechRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPEECHREQUEST,
  __module__ = 'speech_pb2'
  # @@protoc_insertion_point(class_scope:speech.SpeechRequest)
  ))
_sym_db.RegisterMessage(SpeechRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030is.hello.speech.core.apiB\006Speech'))
# @@protoc_insertion_point(module_scope)
