// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voice_responses.proto

package is.hello.speech.core.api;

public final class Text2SpeechQueue {
  private Text2SpeechQueue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SynthesizeMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 voice_response_id = 1;
    /**
     * <code>optional int64 voice_response_id = 1;</code>
     */
    boolean hasVoiceResponseId();
    /**
     * <code>optional int64 voice_response_id = 1;</code>
     */
    long getVoiceResponseId();

    // optional string text = 2;
    /**
     * <code>optional string text = 2;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    // optional .SynthesizeMessage.IntentType intent = 3;
    /**
     * <code>optional .SynthesizeMessage.IntentType intent = 3;</code>
     */
    boolean hasIntent();
    /**
     * <code>optional .SynthesizeMessage.IntentType intent = 3;</code>
     */
    is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType getIntent();

    // optional .SynthesizeMessage.ActionType action = 4;
    /**
     * <code>optional .SynthesizeMessage.ActionType action = 4;</code>
     */
    boolean hasAction();
    /**
     * <code>optional .SynthesizeMessage.ActionType action = 4;</code>
     */
    is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType getAction();

    // optional .SynthesizeMessage.CategoryType category = 5;
    /**
     * <code>optional .SynthesizeMessage.CategoryType category = 5;</code>
     */
    boolean hasCategory();
    /**
     * <code>optional .SynthesizeMessage.CategoryType category = 5;</code>
     */
    is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType getCategory();

    // optional string parameters_string = 6;
    /**
     * <code>optional string parameters_string = 6;</code>
     */
    boolean hasParametersString();
    /**
     * <code>optional string parameters_string = 6;</code>
     */
    java.lang.String getParametersString();
    /**
     * <code>optional string parameters_string = 6;</code>
     */
    com.google.protobuf.ByteString
        getParametersStringBytes();

    // optional .SynthesizeMessage.ServiceType service = 7;
    /**
     * <code>optional .SynthesizeMessage.ServiceType service = 7;</code>
     */
    boolean hasService();
    /**
     * <code>optional .SynthesizeMessage.ServiceType service = 7;</code>
     */
    is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType getService();

    // optional .SynthesizeMessage.VoiceType voice = 8;
    /**
     * <code>optional .SynthesizeMessage.VoiceType voice = 8;</code>
     */
    boolean hasVoice();
    /**
     * <code>optional .SynthesizeMessage.VoiceType voice = 8;</code>
     */
    is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType getVoice();

    // optional .SynthesizeMessage.ResponseType response_type = 9;
    /**
     * <code>optional .SynthesizeMessage.ResponseType response_type = 9;</code>
     */
    boolean hasResponseType();
    /**
     * <code>optional .SynthesizeMessage.ResponseType response_type = 9;</code>
     */
    is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType getResponseType();
  }
  /**
   * Protobuf type {@code SynthesizeMessage}
   */
  public static final class SynthesizeMessage extends
      com.google.protobuf.GeneratedMessage
      implements SynthesizeMessageOrBuilder {
    // Use SynthesizeMessage.newBuilder() to construct.
    private SynthesizeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SynthesizeMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SynthesizeMessage defaultInstance;
    public static SynthesizeMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SynthesizeMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SynthesizeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              voiceResponseId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              text_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType value = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                intent_ = value;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType value = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                action_ = value;
              }
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType value = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                category_ = value;
              }
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              parametersString_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType value = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                service_ = value;
              }
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType value = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                voice_ = value;
              }
              break;
            }
            case 72: {
              int rawValue = input.readEnum();
              is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType value = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(9, rawValue);
              } else {
                bitField0_ |= 0x00000100;
                responseType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return is.hello.speech.core.api.Text2SpeechQueue.internal_static_SynthesizeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return is.hello.speech.core.api.Text2SpeechQueue.internal_static_SynthesizeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.class, is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SynthesizeMessage> PARSER =
        new com.google.protobuf.AbstractParser<SynthesizeMessage>() {
      public SynthesizeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SynthesizeMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SynthesizeMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code SynthesizeMessage.IntentType}
     */
    public enum IntentType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SLEEP_SOUNDS = 1;</code>
       */
      SLEEP_SOUNDS(0, 1),
      /**
       * <code>ALARM = 2;</code>
       */
      ALARM(1, 2),
      /**
       * <code>SLEEP_REPORT = 3;</code>
       */
      SLEEP_REPORT(2, 3),
      /**
       * <code>ROOM_CONDITIONS = 4;</code>
       */
      ROOM_CONDITIONS(3, 4),
      ;

      /**
       * <code>SLEEP_SOUNDS = 1;</code>
       */
      public static final int SLEEP_SOUNDS_VALUE = 1;
      /**
       * <code>ALARM = 2;</code>
       */
      public static final int ALARM_VALUE = 2;
      /**
       * <code>SLEEP_REPORT = 3;</code>
       */
      public static final int SLEEP_REPORT_VALUE = 3;
      /**
       * <code>ROOM_CONDITIONS = 4;</code>
       */
      public static final int ROOM_CONDITIONS_VALUE = 4;


      public final int getNumber() { return value; }

      public static IntentType valueOf(int value) {
        switch (value) {
          case 1: return SLEEP_SOUNDS;
          case 2: return ALARM;
          case 3: return SLEEP_REPORT;
          case 4: return ROOM_CONDITIONS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IntentType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<IntentType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IntentType>() {
              public IntentType findValueByNumber(int number) {
                return IntentType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final IntentType[] VALUES = values();

      public static IntentType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private IntentType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SynthesizeMessage.IntentType)
    }

    /**
     * Protobuf enum {@code SynthesizeMessage.ActionType}
     */
    public enum ActionType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PLAY_SOUND = 1;</code>
       */
      PLAY_SOUND(0, 1),
      /**
       * <code>STOP_SOUND = 2;</code>
       */
      STOP_SOUND(1, 2),
      /**
       * <code>GET_CONDITION = 3;</code>
       *
       * <pre>
       * overall condition
       * </pre>
       */
      GET_CONDITION(2, 3),
      /**
       * <code>GET_SENSOR = 4;</code>
       */
      GET_SENSOR(3, 4),
      ;

      /**
       * <code>PLAY_SOUND = 1;</code>
       */
      public static final int PLAY_SOUND_VALUE = 1;
      /**
       * <code>STOP_SOUND = 2;</code>
       */
      public static final int STOP_SOUND_VALUE = 2;
      /**
       * <code>GET_CONDITION = 3;</code>
       *
       * <pre>
       * overall condition
       * </pre>
       */
      public static final int GET_CONDITION_VALUE = 3;
      /**
       * <code>GET_SENSOR = 4;</code>
       */
      public static final int GET_SENSOR_VALUE = 4;


      public final int getNumber() { return value; }

      public static ActionType valueOf(int value) {
        switch (value) {
          case 1: return PLAY_SOUND;
          case 2: return STOP_SOUND;
          case 3: return GET_CONDITION;
          case 4: return GET_SENSOR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ActionType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
              public ActionType findValueByNumber(int number) {
                return ActionType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final ActionType[] VALUES = values();

      public static ActionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ActionType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SynthesizeMessage.ActionType)
    }

    /**
     * Protobuf enum {@code SynthesizeMessage.CategoryType}
     */
    public enum CategoryType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 1;</code>
       */
      DEFAULT(0, 1),
      /**
       * <code>SOUND_NAME = 2;</code>
       */
      SOUND_NAME(1, 2),
      /**
       * <code>SOUND_DURATION = 3;</code>
       */
      SOUND_DURATION(2, 3),
      /**
       * <code>SOUND_NAME_DURATION = 4;</code>
       */
      SOUND_NAME_DURATION(3, 4),
      /**
       * <code>OVERALL_CONDITIONS = 5;</code>
       */
      OVERALL_CONDITIONS(4, 5),
      /**
       * <code>TEMPERATURE = 6;</code>
       */
      TEMPERATURE(5, 6),
      /**
       * <code>HUMIDITY = 7;</code>
       */
      HUMIDITY(6, 7),
      /**
       * <code>LIGHT = 8;</code>
       */
      LIGHT(7, 8),
      /**
       * <code>AIR_QUALITY = 9;</code>
       */
      AIR_QUALITY(8, 9),
      /**
       * <code>SOUND = 10;</code>
       */
      SOUND(9, 10),
      ;

      /**
       * <code>DEFAULT = 1;</code>
       */
      public static final int DEFAULT_VALUE = 1;
      /**
       * <code>SOUND_NAME = 2;</code>
       */
      public static final int SOUND_NAME_VALUE = 2;
      /**
       * <code>SOUND_DURATION = 3;</code>
       */
      public static final int SOUND_DURATION_VALUE = 3;
      /**
       * <code>SOUND_NAME_DURATION = 4;</code>
       */
      public static final int SOUND_NAME_DURATION_VALUE = 4;
      /**
       * <code>OVERALL_CONDITIONS = 5;</code>
       */
      public static final int OVERALL_CONDITIONS_VALUE = 5;
      /**
       * <code>TEMPERATURE = 6;</code>
       */
      public static final int TEMPERATURE_VALUE = 6;
      /**
       * <code>HUMIDITY = 7;</code>
       */
      public static final int HUMIDITY_VALUE = 7;
      /**
       * <code>LIGHT = 8;</code>
       */
      public static final int LIGHT_VALUE = 8;
      /**
       * <code>AIR_QUALITY = 9;</code>
       */
      public static final int AIR_QUALITY_VALUE = 9;
      /**
       * <code>SOUND = 10;</code>
       */
      public static final int SOUND_VALUE = 10;


      public final int getNumber() { return value; }

      public static CategoryType valueOf(int value) {
        switch (value) {
          case 1: return DEFAULT;
          case 2: return SOUND_NAME;
          case 3: return SOUND_DURATION;
          case 4: return SOUND_NAME_DURATION;
          case 5: return OVERALL_CONDITIONS;
          case 6: return TEMPERATURE;
          case 7: return HUMIDITY;
          case 8: return LIGHT;
          case 9: return AIR_QUALITY;
          case 10: return SOUND;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CategoryType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CategoryType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CategoryType>() {
              public CategoryType findValueByNumber(int number) {
                return CategoryType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.getDescriptor().getEnumTypes().get(2);
      }

      private static final CategoryType[] VALUES = values();

      public static CategoryType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CategoryType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SynthesizeMessage.CategoryType)
    }

    /**
     * Protobuf enum {@code SynthesizeMessage.ServiceType}
     */
    public enum ServiceType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WATSON = 1;</code>
       */
      WATSON(0, 1),
      ;

      /**
       * <code>WATSON = 1;</code>
       */
      public static final int WATSON_VALUE = 1;


      public final int getNumber() { return value; }

      public static ServiceType valueOf(int value) {
        switch (value) {
          case 1: return WATSON;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ServiceType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ServiceType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServiceType>() {
              public ServiceType findValueByNumber(int number) {
                return ServiceType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.getDescriptor().getEnumTypes().get(3);
      }

      private static final ServiceType[] VALUES = values();

      public static ServiceType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ServiceType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SynthesizeMessage.ServiceType)
    }

    /**
     * Protobuf enum {@code SynthesizeMessage.VoiceType}
     */
    public enum VoiceType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALLISON = 1;</code>
       */
      ALLISON(0, 1),
      /**
       * <code>MICHAEL = 2;</code>
       */
      MICHAEL(1, 2),
      ;

      /**
       * <code>ALLISON = 1;</code>
       */
      public static final int ALLISON_VALUE = 1;
      /**
       * <code>MICHAEL = 2;</code>
       */
      public static final int MICHAEL_VALUE = 2;


      public final int getNumber() { return value; }

      public static VoiceType valueOf(int value) {
        switch (value) {
          case 1: return ALLISON;
          case 2: return MICHAEL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<VoiceType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<VoiceType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<VoiceType>() {
              public VoiceType findValueByNumber(int number) {
                return VoiceType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.getDescriptor().getEnumTypes().get(4);
      }

      private static final VoiceType[] VALUES = values();

      public static VoiceType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private VoiceType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SynthesizeMessage.VoiceType)
    }

    /**
     * Protobuf enum {@code SynthesizeMessage.ResponseType}
     */
    public enum ResponseType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 1;</code>
       */
      SUCCESS(0, 1),
      /**
       * <code>FAILURE = 2;</code>
       */
      FAILURE(1, 2),
      /**
       * <code>IDK = 3;</code>
       */
      IDK(2, 3),
      /**
       * <code>TIMEOUT = 4;</code>
       */
      TIMEOUT(3, 4),
      /**
       * <code>NETWORK_ERROR = 5;</code>
       */
      NETWORK_ERROR(4, 5),
      /**
       * <code>API_ERROR = 6;</code>
       */
      API_ERROR(5, 6),
      /**
       * <code>UNKNOWN_ERROR = 7;</code>
       */
      UNKNOWN_ERROR(6, 7),
      ;

      /**
       * <code>SUCCESS = 1;</code>
       */
      public static final int SUCCESS_VALUE = 1;
      /**
       * <code>FAILURE = 2;</code>
       */
      public static final int FAILURE_VALUE = 2;
      /**
       * <code>IDK = 3;</code>
       */
      public static final int IDK_VALUE = 3;
      /**
       * <code>TIMEOUT = 4;</code>
       */
      public static final int TIMEOUT_VALUE = 4;
      /**
       * <code>NETWORK_ERROR = 5;</code>
       */
      public static final int NETWORK_ERROR_VALUE = 5;
      /**
       * <code>API_ERROR = 6;</code>
       */
      public static final int API_ERROR_VALUE = 6;
      /**
       * <code>UNKNOWN_ERROR = 7;</code>
       */
      public static final int UNKNOWN_ERROR_VALUE = 7;


      public final int getNumber() { return value; }

      public static ResponseType valueOf(int value) {
        switch (value) {
          case 1: return SUCCESS;
          case 2: return FAILURE;
          case 3: return IDK;
          case 4: return TIMEOUT;
          case 5: return NETWORK_ERROR;
          case 6: return API_ERROR;
          case 7: return UNKNOWN_ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
              public ResponseType findValueByNumber(int number) {
                return ResponseType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.getDescriptor().getEnumTypes().get(5);
      }

      private static final ResponseType[] VALUES = values();

      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResponseType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SynthesizeMessage.ResponseType)
    }

    private int bitField0_;
    // optional int64 voice_response_id = 1;
    public static final int VOICE_RESPONSE_ID_FIELD_NUMBER = 1;
    private long voiceResponseId_;
    /**
     * <code>optional int64 voice_response_id = 1;</code>
     */
    public boolean hasVoiceResponseId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 voice_response_id = 1;</code>
     */
    public long getVoiceResponseId() {
      return voiceResponseId_;
    }

    // optional string text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 2;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .SynthesizeMessage.IntentType intent = 3;
    public static final int INTENT_FIELD_NUMBER = 3;
    private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType intent_;
    /**
     * <code>optional .SynthesizeMessage.IntentType intent = 3;</code>
     */
    public boolean hasIntent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .SynthesizeMessage.IntentType intent = 3;</code>
     */
    public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType getIntent() {
      return intent_;
    }

    // optional .SynthesizeMessage.ActionType action = 4;
    public static final int ACTION_FIELD_NUMBER = 4;
    private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType action_;
    /**
     * <code>optional .SynthesizeMessage.ActionType action = 4;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .SynthesizeMessage.ActionType action = 4;</code>
     */
    public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType getAction() {
      return action_;
    }

    // optional .SynthesizeMessage.CategoryType category = 5;
    public static final int CATEGORY_FIELD_NUMBER = 5;
    private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType category_;
    /**
     * <code>optional .SynthesizeMessage.CategoryType category = 5;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .SynthesizeMessage.CategoryType category = 5;</code>
     */
    public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType getCategory() {
      return category_;
    }

    // optional string parameters_string = 6;
    public static final int PARAMETERS_STRING_FIELD_NUMBER = 6;
    private java.lang.Object parametersString_;
    /**
     * <code>optional string parameters_string = 6;</code>
     */
    public boolean hasParametersString() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string parameters_string = 6;</code>
     */
    public java.lang.String getParametersString() {
      java.lang.Object ref = parametersString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parametersString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string parameters_string = 6;</code>
     */
    public com.google.protobuf.ByteString
        getParametersStringBytes() {
      java.lang.Object ref = parametersString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parametersString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .SynthesizeMessage.ServiceType service = 7;
    public static final int SERVICE_FIELD_NUMBER = 7;
    private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType service_;
    /**
     * <code>optional .SynthesizeMessage.ServiceType service = 7;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .SynthesizeMessage.ServiceType service = 7;</code>
     */
    public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType getService() {
      return service_;
    }

    // optional .SynthesizeMessage.VoiceType voice = 8;
    public static final int VOICE_FIELD_NUMBER = 8;
    private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType voice_;
    /**
     * <code>optional .SynthesizeMessage.VoiceType voice = 8;</code>
     */
    public boolean hasVoice() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .SynthesizeMessage.VoiceType voice = 8;</code>
     */
    public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType getVoice() {
      return voice_;
    }

    // optional .SynthesizeMessage.ResponseType response_type = 9;
    public static final int RESPONSE_TYPE_FIELD_NUMBER = 9;
    private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType responseType_;
    /**
     * <code>optional .SynthesizeMessage.ResponseType response_type = 9;</code>
     */
    public boolean hasResponseType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .SynthesizeMessage.ResponseType response_type = 9;</code>
     */
    public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType getResponseType() {
      return responseType_;
    }

    private void initFields() {
      voiceResponseId_ = 0L;
      text_ = "";
      intent_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType.SLEEP_SOUNDS;
      action_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType.PLAY_SOUND;
      category_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType.DEFAULT;
      parametersString_ = "";
      service_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType.WATSON;
      voice_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType.ALLISON;
      responseType_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, voiceResponseId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, intent_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, action_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, category_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getParametersStringBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, service_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, voice_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeEnum(9, responseType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, voiceResponseId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, intent_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, action_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, category_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getParametersStringBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, service_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, voice_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, responseType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SynthesizeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return is.hello.speech.core.api.Text2SpeechQueue.internal_static_SynthesizeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return is.hello.speech.core.api.Text2SpeechQueue.internal_static_SynthesizeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.class, is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.Builder.class);
      }

      // Construct using is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        voiceResponseId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        intent_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType.SLEEP_SOUNDS;
        bitField0_ = (bitField0_ & ~0x00000004);
        action_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType.PLAY_SOUND;
        bitField0_ = (bitField0_ & ~0x00000008);
        category_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType.DEFAULT;
        bitField0_ = (bitField0_ & ~0x00000010);
        parametersString_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        service_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType.WATSON;
        bitField0_ = (bitField0_ & ~0x00000040);
        voice_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType.ALLISON;
        bitField0_ = (bitField0_ & ~0x00000080);
        responseType_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return is.hello.speech.core.api.Text2SpeechQueue.internal_static_SynthesizeMessage_descriptor;
      }

      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage getDefaultInstanceForType() {
        return is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.getDefaultInstance();
      }

      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage build() {
        is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage buildPartial() {
        is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage result = new is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.voiceResponseId_ = voiceResponseId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.intent_ = intent_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.category_ = category_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.parametersString_ = parametersString_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.service_ = service_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.voice_ = voice_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.responseType_ = responseType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage) {
          return mergeFrom((is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage other) {
        if (other == is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.getDefaultInstance()) return this;
        if (other.hasVoiceResponseId()) {
          setVoiceResponseId(other.getVoiceResponseId());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000002;
          text_ = other.text_;
          onChanged();
        }
        if (other.hasIntent()) {
          setIntent(other.getIntent());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasCategory()) {
          setCategory(other.getCategory());
        }
        if (other.hasParametersString()) {
          bitField0_ |= 0x00000020;
          parametersString_ = other.parametersString_;
          onChanged();
        }
        if (other.hasService()) {
          setService(other.getService());
        }
        if (other.hasVoice()) {
          setVoice(other.getVoice());
        }
        if (other.hasResponseType()) {
          setResponseType(other.getResponseType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 voice_response_id = 1;
      private long voiceResponseId_ ;
      /**
       * <code>optional int64 voice_response_id = 1;</code>
       */
      public boolean hasVoiceResponseId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 voice_response_id = 1;</code>
       */
      public long getVoiceResponseId() {
        return voiceResponseId_;
      }
      /**
       * <code>optional int64 voice_response_id = 1;</code>
       */
      public Builder setVoiceResponseId(long value) {
        bitField0_ |= 0x00000001;
        voiceResponseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 voice_response_id = 1;</code>
       */
      public Builder clearVoiceResponseId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        voiceResponseId_ = 0L;
        onChanged();
        return this;
      }

      // optional string text = 2;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 2;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        text_ = value;
        onChanged();
        return this;
      }

      // optional .SynthesizeMessage.IntentType intent = 3;
      private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType intent_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType.SLEEP_SOUNDS;
      /**
       * <code>optional .SynthesizeMessage.IntentType intent = 3;</code>
       */
      public boolean hasIntent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .SynthesizeMessage.IntentType intent = 3;</code>
       */
      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType getIntent() {
        return intent_;
      }
      /**
       * <code>optional .SynthesizeMessage.IntentType intent = 3;</code>
       */
      public Builder setIntent(is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        intent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SynthesizeMessage.IntentType intent = 3;</code>
       */
      public Builder clearIntent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        intent_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.IntentType.SLEEP_SOUNDS;
        onChanged();
        return this;
      }

      // optional .SynthesizeMessage.ActionType action = 4;
      private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType action_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType.PLAY_SOUND;
      /**
       * <code>optional .SynthesizeMessage.ActionType action = 4;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .SynthesizeMessage.ActionType action = 4;</code>
       */
      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType getAction() {
        return action_;
      }
      /**
       * <code>optional .SynthesizeMessage.ActionType action = 4;</code>
       */
      public Builder setAction(is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SynthesizeMessage.ActionType action = 4;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000008);
        action_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ActionType.PLAY_SOUND;
        onChanged();
        return this;
      }

      // optional .SynthesizeMessage.CategoryType category = 5;
      private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType category_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType.DEFAULT;
      /**
       * <code>optional .SynthesizeMessage.CategoryType category = 5;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .SynthesizeMessage.CategoryType category = 5;</code>
       */
      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType getCategory() {
        return category_;
      }
      /**
       * <code>optional .SynthesizeMessage.CategoryType category = 5;</code>
       */
      public Builder setCategory(is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SynthesizeMessage.CategoryType category = 5;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000010);
        category_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.CategoryType.DEFAULT;
        onChanged();
        return this;
      }

      // optional string parameters_string = 6;
      private java.lang.Object parametersString_ = "";
      /**
       * <code>optional string parameters_string = 6;</code>
       */
      public boolean hasParametersString() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string parameters_string = 6;</code>
       */
      public java.lang.String getParametersString() {
        java.lang.Object ref = parametersString_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          parametersString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parameters_string = 6;</code>
       */
      public com.google.protobuf.ByteString
          getParametersStringBytes() {
        java.lang.Object ref = parametersString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parametersString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parameters_string = 6;</code>
       */
      public Builder setParametersString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        parametersString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parameters_string = 6;</code>
       */
      public Builder clearParametersString() {
        bitField0_ = (bitField0_ & ~0x00000020);
        parametersString_ = getDefaultInstance().getParametersString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parameters_string = 6;</code>
       */
      public Builder setParametersStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        parametersString_ = value;
        onChanged();
        return this;
      }

      // optional .SynthesizeMessage.ServiceType service = 7;
      private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType service_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType.WATSON;
      /**
       * <code>optional .SynthesizeMessage.ServiceType service = 7;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .SynthesizeMessage.ServiceType service = 7;</code>
       */
      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType getService() {
        return service_;
      }
      /**
       * <code>optional .SynthesizeMessage.ServiceType service = 7;</code>
       */
      public Builder setService(is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SynthesizeMessage.ServiceType service = 7;</code>
       */
      public Builder clearService() {
        bitField0_ = (bitField0_ & ~0x00000040);
        service_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ServiceType.WATSON;
        onChanged();
        return this;
      }

      // optional .SynthesizeMessage.VoiceType voice = 8;
      private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType voice_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType.ALLISON;
      /**
       * <code>optional .SynthesizeMessage.VoiceType voice = 8;</code>
       */
      public boolean hasVoice() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .SynthesizeMessage.VoiceType voice = 8;</code>
       */
      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType getVoice() {
        return voice_;
      }
      /**
       * <code>optional .SynthesizeMessage.VoiceType voice = 8;</code>
       */
      public Builder setVoice(is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        voice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SynthesizeMessage.VoiceType voice = 8;</code>
       */
      public Builder clearVoice() {
        bitField0_ = (bitField0_ & ~0x00000080);
        voice_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.VoiceType.ALLISON;
        onChanged();
        return this;
      }

      // optional .SynthesizeMessage.ResponseType response_type = 9;
      private is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType responseType_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType.SUCCESS;
      /**
       * <code>optional .SynthesizeMessage.ResponseType response_type = 9;</code>
       */
      public boolean hasResponseType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .SynthesizeMessage.ResponseType response_type = 9;</code>
       */
      public is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType getResponseType() {
        return responseType_;
      }
      /**
       * <code>optional .SynthesizeMessage.ResponseType response_type = 9;</code>
       */
      public Builder setResponseType(is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        responseType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .SynthesizeMessage.ResponseType response_type = 9;</code>
       */
      public Builder clearResponseType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        responseType_ = is.hello.speech.core.api.Text2SpeechQueue.SynthesizeMessage.ResponseType.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SynthesizeMessage)
    }

    static {
      defaultInstance = new SynthesizeMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SynthesizeMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SynthesizeMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SynthesizeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025voice_responses.proto\"\221\007\n\021SynthesizeMe" +
      "ssage\022\031\n\021voice_response_id\030\001 \001(\003\022\014\n\004text" +
      "\030\002 \001(\t\022-\n\006intent\030\003 \001(\0162\035.SynthesizeMessa" +
      "ge.IntentType\022-\n\006action\030\004 \001(\0162\035.Synthesi" +
      "zeMessage.ActionType\0221\n\010category\030\005 \001(\0162\037" +
      ".SynthesizeMessage.CategoryType\022\031\n\021param" +
      "eters_string\030\006 \001(\t\022/\n\007service\030\007 \001(\0162\036.Sy" +
      "nthesizeMessage.ServiceType\022+\n\005voice\030\010 \001" +
      "(\0162\034.SynthesizeMessage.VoiceType\0226\n\rresp" +
      "onse_type\030\t \001(\0162\037.SynthesizeMessage.Resp",
      "onseType\"P\n\nIntentType\022\020\n\014SLEEP_SOUNDS\020\001" +
      "\022\t\n\005ALARM\020\002\022\020\n\014SLEEP_REPORT\020\003\022\023\n\017ROOM_CO" +
      "NDITIONS\020\004\"O\n\nActionType\022\016\n\nPLAY_SOUND\020\001" +
      "\022\016\n\nSTOP_SOUND\020\002\022\021\n\rGET_CONDITION\020\003\022\016\n\nG" +
      "ET_SENSOR\020\004\"\266\001\n\014CategoryType\022\013\n\007DEFAULT\020" +
      "\001\022\016\n\nSOUND_NAME\020\002\022\022\n\016SOUND_DURATION\020\003\022\027\n" +
      "\023SOUND_NAME_DURATION\020\004\022\026\n\022OVERALL_CONDIT" +
      "IONS\020\005\022\017\n\013TEMPERATURE\020\006\022\014\n\010HUMIDITY\020\007\022\t\n" +
      "\005LIGHT\020\010\022\017\n\013AIR_QUALITY\020\t\022\t\n\005SOUND\020\n\"\031\n\013" +
      "ServiceType\022\n\n\006WATSON\020\001\"%\n\tVoiceType\022\013\n\007",
      "ALLISON\020\001\022\013\n\007MICHAEL\020\002\"s\n\014ResponseType\022\013" +
      "\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002\022\007\n\003IDK\020\003\022\013\n\007TIM" +
      "EOUT\020\004\022\021\n\rNETWORK_ERROR\020\005\022\r\n\tAPI_ERROR\020\006" +
      "\022\021\n\rUNKNOWN_ERROR\020\007B,\n\030is.hello.speech.c" +
      "ore.apiB\020Text2SpeechQueue"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SynthesizeMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SynthesizeMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SynthesizeMessage_descriptor,
              new java.lang.String[] { "VoiceResponseId", "Text", "Intent", "Action", "Category", "ParametersString", "Service", "Voice", "ResponseType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
